services:
  nginx:
    # https://hub.docker.com/_/nginx
    container_name: nginx
    image: nginx
    volumes:
      - ./nginx/conf-dev:/etc/nginx/conf.d
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    depends_on:
      - backend
  postgres:
    # https://hub.docker.com/_/postgres
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    shm_size: 128mb
    user: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 2s
      timeout: 5s
      retries: 10
  adminer:
    # https://hub.docker.com/_/adminer
    container_name: adminer
    image: adminer
    ports:
      - 9999:8080
  redis:
    # https://hub.docker.com/_/redis
    container_name: redis
    image: redis
    ports:
      - 6379:6379
  # minio:
  #   # https://hub.docker.com/r/bitnami/minio
  #   container_name: minio
  #   image: bitnami/minio
  #   ports:
  #     - 9000:9000 # API port
  #     - 9001:9001 # RMI port
  #   environment:
  #     - MINIO_ROOT_USER=${MINIO_ROOT_USER}
  #     - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
  frontend:
    container_name: frontend
    build:
      context: ../frontend
      dockerfile: ../infra/frontend/Dockerfile
    volumes:
      - ../frontend:/app
    command: bash -c "npm install && npm run dev"
    ports:
      - 8080:5173
  backend:
    container_name: backend
    build:
      context: ../backend
      dockerfile: ../infra/backend/Dockerfile
    volumes:
      - ../backend:/code
    command: flask run --debug
    ports:
      - 8888:5000
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy