services:
  nginx:
    # https://hub.docker.com/_/nginx
    container_name: nginx
    image: nginx
    volumes:
      - ./nginx/conf-prod:/etc/nginx/conf.d:ro
      - ./prod-build:/usr/share/nginx/html
      - ./ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOST=localhost
    depends_on:
      backend:
        condition: service_started
      frontend-builder:
        condition: service_completed_successfully
      ssl-generator:
        condition: service_completed_successfully
  ssl-generator:
    # https://hub.docker.com/_/alpine
    container_name: ssl-generator
    image: alpine
    volumes:
      - ./ssl:/ssl
    command: /ssl/keygen.sh
  postgres:
    # https://hub.docker.com/_/postgres
    container_name: postgres
    image: postgres
    shm_size: 128mb
    user: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 2s
      timeout: 5s
      retries: 10
  adminer:
    # https://hub.docker.com/_/adminer
    container_name: adminer
    image: adminer
    ports:
      - 9999:8080
  redis:
    # https://hub.docker.com/_/redis
    container_name: redis
    image: redis
  frontend-builder:
    container_name: frontend-builder
    build:
      context: ../frontend
      dockerfile: ../infra/frontend-builder/Dockerfile
    volumes:
      - ../frontend:/app
      - ./prod-build:/app/dist
    command: bash -c "npm install && npm run build"
  backend:
    container_name: backend
    build:
      context: ../backend
      dockerfile: ../infra/backend/Dockerfile
    volumes:
      - ../backend:/code
    command: flask run
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy